/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule EditPokemonPage_pokemon.graphql
 * @generated SignedSource<<13abc9c94d6b1be21905a6ec6fb66464>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type EditPokemonPage_pokemon = {|
  +id: string;
  +name: ?string;
  +url: ?string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "EditPokemonPage_pokemon",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "url",
      "storageKey": null
    }
  ],
  "type": "Pokemon"
};

module.exports = fragment;
