/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ListPageQuery.graphql
 * @generated SignedSource<<541aa72b5dc79df33aace6cc90240650>>
 * @relayHash 442dbad8e74001444d88829684d89447
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query ListPageQuery {
  viewer {
    allPokemons(first: 100) {
      ...PokemonList
    }
    id
  }
}

fragment PokemonList on PokemonConnection {
  edges {
    node {
      id
      ...PokemonPreview_pokemon
    }
  }
}

fragment PokemonPreview_pokemon on Pokemon {
  id
  name
  url
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "ListPageQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "first",
                "value": 100,
                "type": "Int"
              }
            ],
            "concreteType": "PokemonConnection",
            "name": "allPokemons",
            "plural": false,
            "selections": [
              {
                "kind": "FragmentSpread",
                "name": "PokemonList",
                "args": null
              }
            ],
            "storageKey": "allPokemons{\"first\":100}"
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "ListPageQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "ListPageQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "first",
                "value": 100,
                "type": "Int"
              }
            ],
            "concreteType": "PokemonConnection",
            "name": "allPokemons",
            "plural": false,
            "selections": [
              {
                "kind": "InlineFragment",
                "type": "PokemonConnection",
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "PokemonEdge",
                    "name": "edges",
                    "plural": true,
                    "selections": [
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "Pokemon",
                        "name": "node",
                        "plural": false,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "id",
                            "storageKey": null
                          },
                          {
                            "kind": "InlineFragment",
                            "type": "Pokemon",
                            "selections": [
                              {
                                "kind": "ScalarField",
                                "alias": null,
                                "args": null,
                                "name": "name",
                                "storageKey": null
                              },
                              {
                                "kind": "ScalarField",
                                "alias": null,
                                "args": null,
                                "name": "url",
                                "storageKey": null
                              }
                            ]
                          }
                        ],
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": "allPokemons{\"first\":100}"
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query ListPageQuery {\n  viewer {\n    allPokemons(first: 100) {\n      ...PokemonList\n    }\n    id\n  }\n}\n\nfragment PokemonList on PokemonConnection {\n  edges {\n    node {\n      id\n      ...PokemonPreview_pokemon\n    }\n  }\n}\n\nfragment PokemonPreview_pokemon on Pokemon {\n  id\n  name\n  url\n}\n"
};

module.exports = batch;
